# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8035986cf1e4a7c9dbcefaa352315c1991e38769769bbb0278b71d61979d20ee64be5371fdeb12abb662492f70dcc4c2de09913685f874bba77abf89c393739

test:
  secret_key_base: 6cf303c374771082ec0911da1af166bef966c9aa94328106da718c82bd639453adef29039f922cc6cd4d04cb4dfb22226e39f455f5c132fa27193b6e019624df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
